Use rich text for supporter notes
openlibhums/consortial_billing pull request #88
Opened 2024-11-13 16:41 UTC by joemull

Closes #83.

2024-11-13 17:12 UTC, ajrbyers requested changes

2024-11-13 17:12 UTC, ajrbyers commented on models.py
>          max_length=500,
I think it wise to drop `max_length`. Its not enforced on the database anyway.

2024-11-15 09:58 UTC, ajrbyers approved these changes

2024-11-28 09:57 UTC, mauromsl approved these changes

2024-11-28 09:57 UTC, merged